'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={projects:[],project:null},tab='overview',submitAction=null,initial='',busy=false;
const status=s=>({missing:'A revisar',stale:'Revisão vencida',current:'Revisado'})[s]||s;
const badge=a=>`<span class="badge ${esc(a.review.status)}">${status(a.review.status)}</span>`;
function notice(text){$('#notice').hidden=false;$('#notice').textContent=text;}
async function api(path,data,method='POST') {const r=await fetch(path,data?{method,headers:{'Content-Type':'application/json','X-Workspace':'1'},body:JSON.stringify(data)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||'Pedido recusado');return j;}
async function load(id=state.project?.id){state=await api('/api/state'+(id?'?project='+encodeURIComponent(id):''));if(!state.project&&state.projects.length){state=await api('/api/state?project='+state.projects[0].id);}render();}
function mutate(path,data,method){return api(path,{...data,project_id:state.project.id,expected_revision:state.project.revision},method);}
function input(name,label,value='',note='',required=true,type='text'){return `<label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}>${note?`<div class="field-note">${note}</div>`:''}`;}
function area(name,label,value='',note=''){return `<label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" class="${name==='markdown'?'markdown':''}" required>${esc(value)}</textarea>${note?`<div class="field-note">${note}</div>`:''}`;}
function sources(selected=[]){return `<fieldset><legend>Fontes vinculadas</legend>${state.project.sources.map(s=>`<label class="check"><input type="checkbox" name="source_ids" value="${s.id}" ${selected.includes(s.id)?'checked':''}>${esc(s.title)} · ${esc(s.version)}</label>`).join('')}</fieldset>`;}
function serial(){return JSON.stringify([...new FormData($('#form')).entries()].map(([k,v])=>[k,v instanceof File?{name:v.name,size:v.size,lastModified:v.lastModified}:v]));}
function open(title,fields,action,label='Salvar'){ $('#form-title').textContent=title;$('#fields').innerHTML=fields;$('#submit').textContent=label;$('#submit').disabled=!action;$('#form-error').hidden=true;$('#discard').hidden=true;submitAction=action;initial=serial();$('#dialog').showModal();}
function close(){if(busy)return;if(serial()!==initial){$('#discard').hidden=false;return;}$('#dialog').close();}
$('#close').onclick=close;$('#cancel').onclick=close;$('#discard-yes').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('cancel',e=>{e.preventDefault();close();});
$('#form').onsubmit=async e=>{e.preventDefault();if(!submitAction||busy)return;busy=true;$('#submit').disabled=true;$('#form-error').hidden=true;try{const fd=new FormData(e.target);const result=await submitAction(fd);if(result?.keepOpen)return;$('#dialog').close();await load(result?.id||state.project?.id);notice(result?.message||'Alteração salva.');}catch(error){$('#form-error').textContent=error.message;$('#form-error').hidden=false;}finally{busy=false;$('#submit').disabled=!submitAction;}};
window.addEventListener('beforeunload',e=>{if($('#dialog').open&&serial()!==initial){e.preventDefault();e.returnValue='';}});
function privateBackup(){
 open('Salvar backup privado',`<div class="boundary"><strong>Este ZIP contém informações internas de todos os projetos.</strong> Inclui fontes, rascunhos, revisões, históricos e publicações preservadas. Guarde em local privado; não envie como central pública. O arquivo não é criptografado.</div><p>O backup copia os dados salvos. Salve qualquer rascunho antes. Sessões, credenciais de acesso e o aplicativo não são incluídos.</p><p>Para recuperar, extraia a distribuição do aplicativo e execute no terminal:</p><pre class="details">python3 backup.py restore workspace-private-backup.zip --to /caminho/novo-workspace</pre><p>O destino deve ser novo e ter uma pasta pai existente. Depois abra com <code>python3 serve.py --store /caminho/novo-workspace --open</code>. A conferência de hashes detecta corrupção, mas não autentica quem criou o backup. Restaure somente um backup próprio e confiável.</p><label class="check"><input name="confirmed" type="checkbox" required>Entendi que este arquivo contém dados privados de todos os projetos.</label>`,async f=>{
  const r=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace':'1'},body:JSON.stringify({private_data_confirmed:f.has('confirmed')})});
  if(!r.ok){const error=await r.json();throw Error(error.error||'Backup recusado');}
  const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='workspace-private-backup.zip';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);
  return {message:'Backup privado preparado. Confira o arquivo na pasta de downloads e guarde uma cópia em local seguro.'};
 },'Baixar backup privado');
}
function project(){open('Comece seu projeto',input('name','Nome público da central')+area('purpose','O que precisa ficar claro para quem usa o produto?','','Contexto interno; não vai para o leitor.')+area('authority','De quem é o conteúdo?','','Registre somente conteúdo próprio. Não inclua contatos ou credenciais.')+area('limits','Limites internos do projeto'),async f=>api('/api/projects',Object.fromEntries(f)),'Criar projeto');}
function source(id){const s=state.project.sources.find(x=>x.id===id)||{};open(s.id?'Atualizar fonte':'Registrar fonte própria',input('title','Título interno',s.title)+input('version','Versão',s.version||'1')+area('content','Conteúdo original',s.content,'Este texto e seu histórico ficam no workspace.')+area('evidence','Como esta informação foi observada?',s.evidence)+area('limits','O que esta fonte não demonstra?',s.limits)+`<label class="check"><input name="original_owned" type="checkbox" required ${s.id?'checked':''}>Declaro que este conteúdo é próprio e posso utilizá-lo.</label>`,async f=>mutate('/api/sources'+(s.id?'/'+s.id:''),{...Object.fromEntries(f),original_owned:f.has('original_owned'),files:s.files||[]},s.id?'PATCH':'POST'));}
function procedure(id){if(!state.project.sources.length)return notice('Registre uma fonte antes do procedimento.');const p=state.project.procedures.find(x=>x.id===id)||{};open(p.id?'Editar procedimento':'Registrar procedimento',input('title','Nome da tarefa',p.title)+area('steps','Passos executados',p.steps)+sources(p.source_ids)+area('evidence','Resultado observado',p.evidence)+area('limits','Pendências e limites',p.limits),async f=>mutate('/api/procedures'+(p.id?'/'+p.id:''),{...Object.fromEntries(f),source_ids:f.getAll('source_ids')},p.id?'PATCH':'POST'));}
function article(id){if(!state.project.sources.length)return notice('Registre uma fonte antes do artigo.');const a=state.project.articles.find(x=>x.id===id)||{};open(a.id?'Editar artigo':'Escrever artigo',input('title','Título público',a.title)+input('slug','Endereço do artigo',a.slug,'Letras minúsculas, números e hífens. Exemplo: configurar-projeto.')+area('markdown','Texto público em Markdown',a.markdown,'Títulos, listas, tabelas simples, código e links HTTPS. HTML e imagens remotas não são publicados.')+area('limits','Limites públicos do procedimento',a.limits,'Este campo aparece junto do artigo na central exportada.')+sources(a.source_ids)+`<label for="f-procedure_id">Procedimento relacionado</label><select id="f-procedure_id" name="procedure_id"><option value="">Sem procedimento</option>${state.project.procedures.map(p=>`<option value="${p.id}" ${a.procedure_id===p.id?'selected':''}>${esc(p.title)}</option>`).join('')}</select>`+area('evidence','Evidência interna para a revisão',a.evidence,'Esta evidência não é exportada na central pública.'),async f=>mutate('/api/articles'+(a.id?'/'+a.id:''),{...Object.fromEntries(f),source_ids:f.getAll('source_ids'),procedure_id:f.get('procedure_id')||null},a.id?'PATCH':'POST'));}

function importDocs(){
 open('Trazer documentação existente',`<p>Selecione até 32 arquivos Markdown próprios, total de 128 KiB UTF-8. Primeiro você verá uma prévia; nada será salvo ainda.</p><label for="f-documents">Arquivos .md</label><input id="f-documents" name="documents" type="file" accept=".md" multiple required>`+area('limits','Limites públicos comuns aos artigos','','Aparecem no leitor. Depois você pode ajustar cada artigo.')+`<label class="check"><input name="original_owned" type="checkbox" required>Os textos são próprios e posso utilizá-los.</label><p class="field-note">Sem sobrescrita. Imagens, front matter, links por referência e links locais fora do lote precisam ser preparados antes.</p>`,async f=>{
  const chosen=f.getAll('documents');if(!chosen.length||chosen.length>32||chosen.reduce((n,x)=>n+x.size,0)>131072)throw Error('Escolha de 1 a 32 arquivos, total até 128 KiB.');
  const files=[];for(const file of chosen){let content;try{content=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());}catch(e){throw Error(file.name+': arquivo precisa de UTF-8 válido.');}files.push({name:file.name,content});}
  const request={files,limits:f.get('limits'),original_owned:f.has('original_owned'),project_id:state.project.id,expected_revision:state.project.revision};
  const preview=await api('/api/import/preview',request);
  open('Conferir lote antes de importar',`<p>${preview.files.length} arquivo(s) · ${preview.total_bytes} bytes. Cada arquivo cria uma fonte original e um artigo sem revisão. O lote inteiro será salvo ou recusado.</p><div class="boundary">${preview.can_apply?'Lote pronto para sua conferência.':'Há conflitos. Corrija os arquivos e selecione o lote novamente; nada foi salvo.'}</div>`+preview.files.map(x=>`<details class="strip"><summary>${esc(x.name)} → ${esc(x.slug)} · ${x.links_changed} link(s) adaptado(s)${x.title_extracted?" · título extraído":""}</summary><h3>${esc(x.title)}</h3>${x.errors.map(e=>`<p class="import-error">${esc(e)}</p>`).join('')}<p>${esc(x.warnings.join(' '))}</p><p>Original SHA-256: <code>${esc(x.sha256)}</code></p><h4>Texto original preservado</h4><pre class="details">${esc(x.original)}</pre><h4>Rascunho a criar</h4><pre class="details">${esc(x.markdown)}</pre></details>`).join('')+`<p><strong>Limites públicos:</strong> ${esc(preview.limits)}</p>`+(preview.can_apply?`<label class="check"><input name="confirmed" type="checkbox" required>Conferi o lote e autorizo criar estes rascunhos, ainda sem aprovação.</label>`:''),preview.can_apply?async approval=>{const result=await api('/api/import/apply',{...request,plan:preview.plan,confirmed:approval.has('confirmed')});tab='articles';return result;}:null,'Importar rascunhos');
  return {keepOpen:true};
 },'Conferir lote');
}

function importedArticle(id){return state.project.history.flatMap(h=>h.action==='markdown_batch_imported'?h.details.files:[]).find(f=>f.article_id===id);}
function updateDoc(id){
 const origin=importedArticle(id);if(!origin)return notice('Este artigo não veio do importador.');
 const a=state.project.articles.find(x=>x.id===id);
 open('Atualizar documento importado',`<p>Escolha a nova versão de <strong>${esc(origin.original_name)}</strong>. Você verá as diferenças antes de salvar a fonte e o artigo juntos. Edições feitas no artigo serão substituídas apenas após sua confirmação.</p><label for="f-document">Arquivo .md atualizado</label><input id="f-document" name="document" type="file" accept=".md" required><label class="check"><input name="original_owned" type="checkbox" required>O documento é próprio e posso utilizá-lo.</label>`,async f=>{
  const file=f.get('document');if(!file||file.size>131072)throw Error('Escolha um arquivo de até 128 KiB.');
  let content;try{content=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());}catch(e){throw Error('O arquivo precisa de UTF-8 válido.');}
  const request={project_id:state.project.id,expected_revision:state.project.revision,article_id:id,original_owned:f.has('original_owned'),files:[{name:file.name,content}]};
  const v=await api('/api/import/update-preview',request);
  open('Conferir atualização',`<p><strong>${esc(v.name)}</strong> → ${esc(v.slug)} · ${v.links_changed} link(s) adaptado(s).</p><div class="boundary">${!v.changed?'Nenhuma alteração. Nada será salvo.':v.errors.length?'Há conflitos; nada será salvo.':'A confirmação salva fonte e artigo juntos. Os artigos dependentes exigirão nova revisão; publicações anteriores permanecem intactas.'}</div>${v.errors.map(x=>`<p class="import-error">${esc(x)}</p>`).join('')}<h3>Artigos que dependem desta fonte</h3><ul>${v.affected_articles.map(x=>`<li>${esc(x.title)}</li>`).join('')}</ul>${[['title','Título público'],['markdown','Texto público'],['original','Fonte interna']].map(([key,label])=>`<details class="strip"><summary>${label}: antes e depois</summary><h4>Antes</h4><pre class="details">${esc(v.before[key])}</pre><h4>Depois</h4><pre class="details">${esc(v.after[key])}</pre><h4>Diferenças (− removido, + adicionado)</h4><pre class="details">${esc(v.diffs[key]||'Sem alteração neste campo.')}</pre></details>`).join('')}<p><strong>Limites públicos preservados:</strong> ${esc(v.limits)}</p>`+(v.can_apply?'<label class="check"><input name="confirmed" type="checkbox" required>Conferi as diferenças e autorizo substituir o rascunho por esta versão, preservando o histórico.</label>':''),v.can_apply?async f=>api('/api/import/update-apply',{...request,plan:v.plan,confirmed:f.has('confirmed')}):null,'Salvar atualização');
  return {keepOpen:true};
 },'Comparar versões');
}
function updateHistory(id){
 const rows=state.project.history.filter(h=>h.action==='markdown_file_updated'&&h.details.article_id===id);
 open('Versões anteriores do artigo',rows.length?rows.map(h=>`<details class="strip"><summary>${esc(new Date(h.created_at).toLocaleString('pt-BR'))} · revisão anterior ${h.details.previous_article.revision}</summary><h3>${esc(h.details.previous_article.title)}</h3><pre class="details">${esc(h.details.previous_article.markdown)}</pre><p>Limites: ${esc(h.details.previous_article.limits)}</p><p>Registro preservado. Para a fonte original, consulte Fontes → Histórico.</p></details>`).join(''):'<p>Nenhuma atualização por arquivo ainda.</p>',null);
}

function reviewer(){return input('reviewer','Identificador local do revisor','','Use um apelido local, não e-mail ou dados pessoais.')+`<label for="f-kind">Tipo de revisão</label><select id="f-kind" name="kind"><option value="operator">Operador</option><option value="ai_assisted">Assistida por IA</option></select>`;}
function actor(f){return {kind:f.get('kind'),label:f.get('reviewer')};}
function review(id){const a=state.project.articles.find(x=>x.id===id);const ids=new Set(a.source_ids);const p=state.project.procedures.find(x=>x.id===a.procedure_id);(p?.source_ids||[]).forEach(x=>ids.add(x));open('Conferir a versão salva',`<h3>${esc(a.title)}</h3><iframe class="preview" title="Prévia do artigo salvo" sandbox src="/api/preview?project=${state.project.id}&article=${a.id}"></iframe><div class="boundary">A revisão vale para esta versão e suas fontes. A identidade é declarada localmente; não é assinatura verificada ou aceite de cliente.</div>${state.project.sources.filter(s=>ids.has(s.id)).map(s=>`<details><summary>Fonte: ${esc(s.title)} · ${esc(s.version)}</summary><pre class="details">${esc(s.content)}</pre><p>${esc(s.evidence)}</p><p>${esc(s.limits)}</p></details>`).join('')}${p?`<details><summary>Procedimento: ${esc(p.title)}</summary><pre class="details">${esc(p.steps)}</pre><p>${esc(p.evidence)}</p><p>${esc(p.limits)}</p></details>`:''}<p><strong>Evidência do artigo:</strong> ${esc(a.evidence)}</p><p><strong>Limites públicos:</strong> ${esc(a.limits)}</p>`+reviewer()+area('note','O que você conferiu?')+`<label class="check"><input name="confirmed" type="checkbox" required>Conferi o artigo salvo, as fontes e os limites desta versão.</label>`,async f=>mutate('/api/articles/'+a.id+'/review',{actor:actor(f),note:f.get('note')}),'Registrar revisão');}
function publish(){open('Produzir central de ajuda',`<div class="boundary"><strong>Campos públicos:</strong> nome da central, títulos, texto dos artigos e limites públicos. Fontes, evidências e notas de revisão ficam no workspace. Confira o conteúdo: o sistema não detecta segredos escritos no texto público.</div><ul>${state.project.articles.map(a=>`<li>${esc(a.title)} — ${status(a.review.status)}<p>${esc(a.limits)}</p></li>`).join('')}</ul>`+reviewer()+area('note','Nota interna desta publicação')+`<label class="check"><input name="public_fields_reviewed" type="checkbox" required>Revisei os campos públicos e autorizo gerar a central local.</label>`,async f=>mutate('/api/publish',{actor:actor(f),note:f.get('note'),public_fields_reviewed:f.has('public_fields_reviewed')}),'Gerar central');}
function activate(id){open('Selecionar versão preservada',`<p>Selecionar esta publicação altera apenas a versão ativa. Os rascunhos e fontes atuais continuam como estão.</p>`+reviewer()+area('note','Motivo da seleção'),async f=>mutate('/api/activate',{release_id:id,actor:actor(f),note:f.get('note')}),'Selecionar publicação');}
async function history(id){try{const list=await api('/api/sources/'+state.project.id+'/'+id+'/history');open('Histórico da fonte',list.map(x=>`<details><summary>Revisão ${x.revision} · ${esc(new Date(x.created_at).toLocaleString('pt-BR'))}</summary><pre class="details">${esc(x.content)}</pre></details>`).join(''),null);}catch(e){notice(e.message);}}
function render(){const p=state.project;$('#title').textContent=p?.name||'Sua próxima central de ajuda.';$('#version').textContent='Versão '+state.version+' · prévia de produto';$('#projects').innerHTML='<option value="">Escolha um projeto</option>'+state.projects.map(x=>`<option value="${x.id}" ${p?.id===x.id?'selected':''}>${esc(x.name)}</option>`).join('');document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));let h='';
if(!p){h=`<section class="hero"><div class="eyebrow">DO PRODUTO À AJUDA UTILIZÁVEL</div><h2>Escreva com fundamento.<br>Publique com revisão.</h2><p>Organize seu conhecimento, vincule cada artigo às fontes e mantenha uma central de ajuda com versões preservadas.</p><button data-action="project">Criar meu primeiro projeto</button></section><div class="grid section-title"><div class="card"><h3>Comece com conteúdo próprio</h3><p>Registre uma fonte, documente a tarefa e escreva o artigo. Você controla o que fica interno e o que entra na central.</p></div><div class="card"><h3>Mudanças que não passam despercebidas</h3><p>Se a fonte mudar, os artigos dependentes precisam de nova revisão antes da próxima publicação.</p></div></div>`;}
else if(tab==='overview'){const pending=p.articles.filter(a=>a.review.status!=='current').length;h=`<section class="hero"><div class="eyebrow">SEU FLUXO EDITORIAL</div><h2>${p.articles.length?(pending?'Há conhecimento para conferir.':'Pronto para preparar sua publicação.'):'Transforme suas fontes em ajuda.'}</h2><p>${esc(p.purpose)}</p><button data-action="${p.sources.length?'article':'source'}">${p.sources.length?'Escrever artigo':'Registrar primeira fonte'}</button></section><div class="stats"><div class="stat"><b>${p.sources.length}</b><span>FONTES REGISTRADAS</span></div><div class="stat"><b>${pending}</b><span>ARTIGOS A REVISAR</span></div><div class="stat"><b>${p.releases.length}</b><span>PUBLICAÇÕES</span></div></div><div class="grid"><div class="card"><h3>Um caminho até a central</h3><ol class="steps"><li>Registre fontes e procedimentos próprios.</li><li>Escreva artigos e escolha seus fundamentos.</li><li>Confira a versão salva e registre a revisão.</li><li>Gere, leia e exporte a central de ajuda.</li></ol></div><div class="card"><h3>Precisa de atenção</h3>${pending?p.articles.filter(a=>a.review.status!=='current').map(a=>`<div class="strip"><p>${esc(a.title)}</p>${badge(a)} <button class="secondary" data-action="review" data-id="${a.id}">Conferir</button></div>`).join(''):'<p>Nenhuma revisão pendente. A revisão editorial não verifica automaticamente a execução do procedimento.</p>'}</div></div>`;}
else if(tab==='articles'){h=`<div class="row section-title"><h2>Artigos</h2><div class="actions"><button class="secondary" data-action="importDocs">Importar Markdown</button><button data-action="article">+ Novo artigo</button></div></div>`+p.articles.map(a=>`<article class="card"><div class="row"><h3>${esc(a.title)}</h3>${badge(a)}</div><p class="muted">${esc(a.slug)} · ${a.source_ids.length} fonte(s) · revisão ${a.revision}</p><p>${esc(a.limits)}</p><div class="actions"><button class="secondary" data-action="article" data-id="${a.id}">Editar</button><button data-action="review" data-id="${a.id}">Conferir e revisar</button>${importedArticle(a.id)?`<button class="secondary" data-action="updateDoc" data-id="${a.id}">Atualizar por arquivo</button><button class="secondary" data-action="updateHistory" data-id="${a.id}">Versões anteriores</button>`:""}</div></article>`).join('');if(!p.articles.length)h+='<div class="empty">Escreva seu primeiro artigo depois de registrar uma fonte.</div>';}
else if(tab==='sources'||tab==='procedures'){let isSource=tab==='sources',items=p[tab],action=isSource?'source':'procedure';h=`<div class="row section-title"><h2>${isSource?'Fontes próprias':'Procedimentos'}</h2><button data-action="${action}">+ ${isSource?'Nova fonte':'Novo procedimento'}</button></div><p class="muted">Informações internas. Alterações vencem as revisões dos artigos dependentes.</p>`+items.map(s=>`<article class="card"><h3>${esc(s.title)}</h3><p class="muted">${isSource?'Versão '+esc(s.version)+' · ':''}Revisão ${s.revision}</p><pre class="details">${esc((s.content||s.steps).slice(0,500))}</pre><div class="actions"><button class="secondary" data-action="${action}" data-id="${s.id}">Editar</button>${isSource?`<button class="secondary" data-action="history" data-id="${s.id}">Histórico</button>`:''}</div></article>`).join('');if(!items.length)h+='<div class="empty">Nenhum registro ainda. Use o botão acima para começar.</div>';}
else if(tab==='releases'){h=`<div class="row section-title"><h2>Publicações</h2><button data-action="publish" ${!p.articles.length?'disabled':''}>Gerar central</button></div><div class="boundary">O download contém somente o leitor público. Ele não é backup do workspace. A prévia é local; hospedar a central é uma ação separada.</div>`+[...p.releases].reverse().map(r=>`<article class="card"><div class="row"><h3>${esc(new Date(r.created_at).toLocaleString('pt-BR'))}</h3>${p.active_release_id===r.id?'<span class="badge current">Ativa</span>':'<span class="badge">Preservada</span>'}</div><p>${esc(r.note)}</p><div class="actions"><a target="_blank" rel="noopener" href="/reader/${p.id}/${r.id}/index.html">Abrir central</a><a href="/api/releases/${p.id}/${r.id}/download" download>Baixar central ZIP</a>${p.active_release_id!==r.id?`<button class="secondary" data-action="activate" data-id="${r.id}">Selecionar versão</button>`:''}</div><details class="strip"><summary>Integridade da publicação</summary><code>${esc(r.manifest_sha256)}</code></details></article>`).join('');if(!p.releases.length)h+='<div class="empty">Os artigos precisam de revisão atual antes de gerar a primeira central.</div>';}
$('#content').innerHTML=h;}
$('#private-backup').onclick=privateBackup;$('#create-project').onclick=project;$('#reload').onclick=()=>load().catch(e=>notice(e.message));$('#projects').onchange=e=>load(e.target.value).catch(e=>notice(e.message));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});$('#content').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;({project,source,procedure,article,review,publish,activate,history,importDocs,updateDoc,updateHistory})[b.dataset.action]?.(b.dataset.id);};
load().catch(e=>notice(e.message));
